import { icons } from "./icons";

export const tabs = [
  {
    name: "index",
    title: "Home",
    icon: icons.home,
  },
  {
    name: "subscriptions",
    title: "Subscriptions",
    icon: icons.wallet,
  },
  {
    name: "insights",
    title: "Insights",
    icon: icons.activity,
  },
  {
    name: "settings",
    title: "Settings",
    icon: icons.setting,
  },
];

export const HOME_USER = {
  name: "Peter Parker",
  email: "peter.parker@starkindustries.com",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Peter",
};

export const HOME_BALANCE = {
  amount: 2449.48,
  currency: "USD",
  nextRenewalDate: "2026-03-18T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
  {
    id: "spotify",
    icon: icons.spotify,
    name: "Spotify",
    price: 5.99,
    currency: "USD",
    daysLeft: 2,
  },
  {
    id: "netflix",
    icon: icons.netflix,
    name: "Netflix",
    price: 15.99,
    currency: "USD",
    daysLeft: 3,
  },
  {
    id: "notion",
    icon: icons.notion,
    name: "Notion",
    price: 12.0,
    currency: "USD",
    daysLeft: 4,
  },
  {
    id: "figma",
    icon: icons.figma,
    name: "Figma",
    price: 15.0,
    currency: "USD",
    daysLeft: 6,
  },
  {
    id: "dropbox",
    icon: icons.dropbox,
    name: "Dropbox",
    price: 9.99,
    currency: "USD",
    daysLeft: 8,
  },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "adobe-creative-cloud",
    icon: icons.adobe,
    name: "Adobe Creative Cloud",
    plan: "Teams Plan",
    category: "Design",
    paymentMethod: "Visa ending in 8530",
    status: "active",
    startDate: "2025-03-20T10:00:00.000Z",
    price: 77.49,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-20T10:00:00.000Z",
    color: "#f5c542",
  },
  {
    id: "netflix-premium",
    icon: icons.netflix,
    name: "Netflix",
    plan: "Premium 4K",
    category: "Entertainment",
    paymentMethod: "Visa ending in 4421",
    status: "active",
    startDate: "2025-01-15T10:00:00.000Z",
    price: 15.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-15T10:00:00.000Z",
    color: "#e50914",
  },
  {
    id: "github-pro",
    icon: icons.github,
    name: "GitHub Pro",
    plan: "Developer",
    category: "Developer Tools",
    paymentMethod: "Mastercard ending in 2408",
    status: "active",
    startDate: "2024-11-24T10:00:00.000Z",
    price: 9.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-24T10:00:00.000Z",
    color: "#e8def8",
  },
  {
    id: "claude-pro",
    icon: icons.claude,
    name: "Claude Pro",
    plan: "Pro Plan",
    category: "AI Tools",
    paymentMethod: "Amex ending in 1010",
    status: "paused",
    startDate: "2025-06-27T10:00:00.000Z",
    price: 20.0,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-27T10:00:00.000Z",
    color: "#b8d4e3",
  },
  {
    id: "openai-plus",
    icon: icons.openai,
    name: "ChatGPT Plus",
    plan: "Plus Plan",
    category: "AI Tools",
    paymentMethod: "Visa ending in 9901",
    status: "active",
    startDate: "2025-02-10T10:00:00.000Z",
    price: 20.0,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-10T10:00:00.000Z",
    color: "#74aa9c",
  },
  {
    id: "spotify-family",
    icon: icons.spotify,
    name: "Spotify",
    plan: "Family",
    category: "Entertainment",
    paymentMethod: "Mastercard ending in 1122",
    status: "active",
    startDate: "2024-12-05T10:00:00.000Z",
    price: 16.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-05T10:00:00.000Z",
    color: "#1db954",
  },
  {
    id: "dropbox-plus",
    icon: icons.dropbox,
    name: "Dropbox",
    plan: "Plus",
    category: "Cloud Storage",
    paymentMethod: "Visa ending in 3344",
    status: "active",
    startDate: "2025-01-20T10:00:00.000Z",
    price: 9.99,
    currency: "USD",
    billing: "Monthly",
    renewalDate: "2026-03-20T10:00:00.000Z",
    color: "#0061ff",
  },
  {
    id: "canva-pro",
    icon: icons.canva,
    name: "Canva Pro",
    plan: "Yearly Access",
    category: "Design",
    paymentMethod: "Visa ending in 7784",
    status: "cancelled",
    startDate: "2024-04-02T10:00:00.000Z",
    price: 119.99,
    currency: "USD",
    billing: "Yearly",
    renewalDate: "2026-04-02T10:00:00.000Z",
    color: "#00c4cc",
  },
];

export const CATEGORIES = [
  "All",
  "Design",
  "Entertainment",
  "Developer Tools",
  "AI Tools",
  "Cloud Storage",
  "Productivity",
];
